<form action="" method="post" class="form-horizontal">
<fieldset>

<!-- Form Name -->
<legend>Inscription</legend>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="username"></label>  
  <div class="col-md-4">
  <input id="username" name="username" type="text" placeholder="Nom" class="form-control input-md">
    
  </div>
</div>

<!-- Password input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="hashedPassword"></label>
  <div class="col-md-4">
    <input id="hashedPassword" name="hashedPassword" type="password" placeholder="Mot de passe" class="form-control input-md">
    
  </div>
</div>

<!-- Button -->
<div class="form-group">
  <label class="col-md-4 control-label" for="Envoyer"></label>
  <div class="col-md-4">
    <button id="Envoyer" name="Envoyer" class="btn btn-danger">Envoyer</button>
  </div>
</div>

</fieldset>
</form>