<?php include('./header.php'); ?>
        <div class="container-fluid">
            <h1>Modifier l'article</h1>
            <form action="redigerunArticle.php.php?id=<?= intval($_GET['id']) ?>" method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <input type="text" name="titre" placeholder="Nouveau titre"/>
                </div>
                <div class="form-group">
                    <input type="file" name="fichier" accept="image/png, image/jpeg">
                    <input type="hidden" name="MAX_FILE_SIZE" value="3000000">
                </div>
                <div class="form-group">
                    <textarea name="contenu" placeholder="Nouveau contenu"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Publier</button>
            </form>
            <?php if(isset($erreur)): ?><p class="erreur"><?= $erreur ?></p><?php endif?>
        </div>